### ISSUE TITLE
Duplicate GraphQL subscriptions sent

### ISSUE THREAD

**Issue by rjwills28** [dls-controls/cs-web-lib#11]
This issue relates to the memory leak found in the Coniql application: https://github.com/dls-controls/coniql/issues/35

While debugging the memory leak in the Coniql application, I came across an issue in the GraphQL subscription mechanism in the cs-web-lib code. I was able to consistently reproduce a case that caused the memory leak in Coniql and one that did not. 

**Memory leak**: This occurs when the a page is loaded which is subscribing to PVs through Coniql, but Coniql has not yet been started (or has been taken down). When the page loads, the `subscribe` commands are sent from the web app. As Coniql has not yet been started, the application performs an `unsubscribe` after a disconnect. When Coniql is started, the web app sends another `subscribe` on reconnection. The previous subscribe on start up has not been cancelled (for some reason) and so 2 subscribes are picked up by Coniql. One of these is old and appears to not be attached to a client - this might be what is causing the memory leak.

**No memory leak**: If Coniql is already running before a web page subscribing to PVs is loaded then there is no memory leak. The `subscribe` is sent once and only once. Note that if you then bring Coniql down and restart it, we will end up in the first situation and get a memory leak. 

Possibly something wrong with the unsubscribe that is not clearing the initial subscription on disconnect.

**Comment by aawdls** [comment]
@AlexanderWells-diamond  We should check whether the same issue exists in the pts app, as likely you followed some similar patterns to cs-web-proto.

**Comment by AlexanderWells-diamond** [comment]
I have certainly seen similar a similar issue - on my development setup I see a GraphQL connection to Coniql established and then closed every minute. Strangely this does not happen in the deployed Production build. I also note that the PTS app does not use the SubscriptionClient, instead using ApolloClient and its `useSubscription` hook. So I suspect its unlikely to be the same issue, but I'll raise one anyway for the weird behaviour in the Development environment.

**Comment by aawdls** [comment]
Fixed with #12
