### ISSUE TITLE
Boolean properties in json file are inconsistent

### ISSUE THREAD

**Issue by rjwills28** [dls-controls/cs-web-lib#46]
As noticed in https://github.com/dls-controls/cs-web-lib/pull/44, in the json file the `scroll` and `executeAsOne` properties take a boolean value, whereas `showCloseButton` takes a boolean wrapped as a string, i.e.
```
"scroll": true,
"executeAsOne": false,
"showCloseButton": "true"
```
I think these should be consistent as it is easy to make a mistake and use the wrong type when creating the json file. Presumably showCloseButton should just be a boolean.

**Comment by abigailalexander** [comment]
Fixed by PR #48
